- name: understand facts
  hosts: centos:ubuntu #all
  become: yes
  tasks:
   - name: print all the facts
     ansible.builtin.debug:
      msg: "All the facts: {{ansible_facts}}"
   #Just imagine we don't have user module available
   - name: add user ubuntu
     ansible.builtin.command: adduser roboshop
     #when: ansible_facts['distribution'] == "Ubuntu"
     when: ansible_os_family == "Ubuntu"
   
   - name: add user in centos
     ansible.builtin.command: useradd roboshop
     when: ansible_facts['distribution'] == "CentOS"
     #when: ansible_os_family == "CentOS"
