- name: DEMO on filters
  hosts: localhost
  vars:
   NAME: Siva Reddy Medam
  become: yes
  tasks:
   - name: convert into upper case
     debug:
      msg: "Hello {{ NAME | upper }}"

   - name: convert into lower case
     debug:
      msg: "Hello {{ NAME | lower }}"