- name: DEMO on filters
  hosts: localhost
  vars:
   NAME: Siva Reddy Medam
   website: https://www.joindevops.com/batch-74s
   Greetings: Hellow Siva, How are you
  become: yes
  tasks:
   - name: convert into upper case
     debug:
      msg: "Hello {{ NAME | upper }}"
   
   - name: convert into lower case
     debug:
      msg: "Hello {{ NAME | lower }}"
   
   - name: printing undefined variable
     debug:
      msg: "Course is: {{ COURSE | default('DevOps') }}"

   - name: extract hostname
     debug:
      msg: "{{ website | urlsplit('hostname') }}"

   - name: split
     debug:
      msg: "{{ Greetings | split(',') }}"